### ISSUE TITLE
Back to top works only once on Chrome

### ISSUE THREAD

**Issue by LucasPadovan** [eventbrite/javascript#15]
Just a minor thing.... I can't find a way to solve this so I'll just leave the comment here.

Pressing "Back to top" on any link will work just once.

I think that happens because we are adding a '#' to the url that makes the page go to the top... but after that nothing will work because the '#' is still there.

**Comment by BenAtEventbrite** [comment]
Yeah, not sure what we can do here. If you click it and don't click any other links, the hash (`#`) isn't actually gonna change. It's the limitation of markdown and what we can do here in Github.  

Gonna close this out.
