### ISSUE TITLE
Bunch of warnings

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/javascript#56]
We are seeing a bunch of warnings when using this configuration in britecharts-react:

![1__bash](https://user-images.githubusercontent.com/9063187/31747954-cc38f610-b424-11e7-9a6a-2a6ed7e5ab9f.png)

It would be lovely if we could update this so they don't show up.

**Comment by prakharcipher** [comment]
I'd like to fix this. Please guide me through the code flow.

**Comment by benmvp** [comment]
The problem was that the docs assumed that we could use latest versions of the packages instead of the specific versions that `eventbrite-react` implicitly needed. We updated the setup instructions: https://github.com/eventbrite/javascript/tree/master/packages/eslint-config-eventbrite-react#usage
