### ISSUE TITLE
Seems to be an error in one example

### ISSUE THREAD

**Issue by SirGrantt** [eventbrite/javascript#75]
Hi, 

I was recently at a conference where someone mentioned your docs here about your coding guidelines and I was browsing your documentation here to try and learn some better practices for writing javascript. While I was reading and working through trying out some examples I noticed something that might be worth pointing out. 

It seems in the section about iterators that the goal is to grab a list of fruits out of the peoplesFavoriteFruits object and place it into the fruits variable. When you copy and paste the //good examples into a repl and run it the Object.keys(peoplesFavoriteFruits).map() function does not return a list of fruits but rather returns the first letter of each property name. I thought for anyone in the future looking through this that it might be a bit confusing so I thought I would mention it here in case that was not the result you were looking to demonstrate. Hope this helps!

edit: not the first letter of each property name, rather the index of the property name in the keys list is being used to grab the corresponding character of the properties name itself at that index point.

**Comment by benmvp** [comment]
Oh interesting! Thanks for pointing it out. Can you link me to the specific piece of the documentation. Or better yet do you think you can fix it and submit a PR? 😄

**Comment by SirGrantt** [comment]
@benmvp I made the changes and submitted the PR. Also, I saw you speak at Music City Code, thank you for your talk, it was great!

**Comment by benmvp** [comment]
Glad to hear it was helpful! Thanks so much!

And thanks too for the PR #76!
